/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AviaryGUI.java
 *
 * Created on May 6, 2011, 1:30:17 AM
 */

package bird;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;

/**
 *
 * @author Dray
 */
public class AviaryGUI extends javax.swing.JFrame {

     String[] parrotPhrases = {"Polly wanna craker! ",
                               "Pieces of eight: Pieces of eight! ",
                               "You're a pretty boy!",
                               "I wonder if this thing can talk?"};

      Bird[] birdArray = { new Ostrich(), new Goose(), new Parrot("green"),
                            new TalkingParrot("red", parrotPhrases), new ScreenOwl(),
                            new SnowOwl() };

      private static Random myRandom = new Random();

    /** Creates new form AviaryGUI */
    public AviaryGUI() {
        initComponents();
        
    }






    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birdJPanel = new javax.swing.JPanel();
        birdJScrollPane = new javax.swing.JScrollPane();
        birdJList = new javax.swing.JList();
        displayScrollPane = new javax.swing.JScrollPane();
        displayJTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab5 extra credits");

        birdJList.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        birdJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Goose", "Ostrich", "Owl", "Parrot", "ScreenOwl", "SnowOwl", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        birdJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                birdJListValueChanged(evt);
            }
        });
        birdJScrollPane.setViewportView(birdJList);

        javax.swing.GroupLayout birdJPanelLayout = new javax.swing.GroupLayout(birdJPanel);
        birdJPanel.setLayout(birdJPanelLayout);
        birdJPanelLayout.setHorizontalGroup(
            birdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(birdJScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        birdJPanelLayout.setVerticalGroup(
            birdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(birdJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );

        displayJTextArea.setColumns(20);
        displayJTextArea.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        displayJTextArea.setRows(5);
        displayScrollPane.setViewportView(displayJTextArea);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(birdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(birdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void birdJListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_birdJListValueChanged
    {//GEN-HEADEREND:event_birdJListValueChanged
        int index = (birdJList.getSelectedIndex());
        if(index == -1)
           index = 0;
        showBirdData(index);
    }//GEN-LAST:event_birdJListValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showBirdData(int index)
    {
        switch(index)
        {
            case 0:
                displayJTextArea.setText(birdArray[0].toString());
                break;
            case 1:
                displayJTextArea.setText(birdArray[1].toString());
                break;
            case 2:
                displayJTextArea.setText(birdArray[2].toString());
                break;
            case 3:
                displayJTextArea.setText(birdArray[3].toString());
                break;
            case 4:
                displayJTextArea.setText(birdArray[4].toString());
                break;
            case 5:
                displayJTextArea.setText(birdArray[5].toString());
                break;
            case 6:
                displayJTextArea.setText(birdArray[6].toString());
                break;
        }

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

                AviaryGUI birdGUI = new AviaryGUI();
                birdGUI.setLocationRelativeTo(null);  // locate this program in the center of screen
                birdGUI.setVisible(true);
                birdGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList birdJList;
    private javax.swing.JPanel birdJPanel;
    private javax.swing.JScrollPane birdJScrollPane;
    private javax.swing.JTextArea displayJTextArea;
    private javax.swing.JScrollPane displayScrollPane;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
