package stack;

import javax.swing.JFrame;

public class StackGUI extends javax.swing.JFrame {

    private StringBuilder display = new StringBuilder("");
    private Stack stackObject;
    private int size;
    /** Creates new form StackGUI */
    public StackGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholeJPanel = new javax.swing.JPanel();
        pushJTextField = new javax.swing.JTextField();
        pushJButton = new javax.swing.JButton();
        popJButton = new javax.swing.JButton();
        displayJButton = new javax.swing.JButton();
        displayJScrollPane = new javax.swing.JScrollPane();
        stackJTextArea = new javax.swing.JTextArea();
        sizeJTextField = new javax.swing.JTextField();
        sizeJButton = new javax.swing.JButton();
        explanationJLabel1 = new javax.swing.JLabel();
        explanationJLabel2 = new javax.swing.JLabel();
        explanationJLabel3 = new javax.swing.JLabel();
        explanationJLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stack");

        wholeJPanel.setBackground(new java.awt.Color(204, 204, 255));

        pushJButton.setText("PUSH");
        pushJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushJButtonActionPerformed(evt);
            }
        });

        popJButton.setText("POP");
        popJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popJButtonActionPerformed(evt);
            }
        });

        displayJButton.setText("DISPLAY");
        displayJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayJButtonActionPerformed(evt);
            }
        });

        stackJTextArea.setColumns(20);
        stackJTextArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        stackJTextArea.setRows(5);
        displayJScrollPane.setViewportView(stackJTextArea);

        sizeJButton.setText("SIZE");
        sizeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeJButtonActionPerformed(evt);
            }
        });

        explanationJLabel1.setText("Makes the stack size");

        explanationJLabel2.setText("Push the data into stack");

        explanationJLabel3.setText("Pop the top data from stack");

        explanationJLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        explanationJLabel4.setText("Developer Dray");

        javax.swing.GroupLayout wholeJPanelLayout = new javax.swing.GroupLayout(wholeJPanel);
        wholeJPanel.setLayout(wholeJPanelLayout);
        wholeJPanelLayout.setHorizontalGroup(
            wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholeJPanelLayout.createSequentialGroup()
                .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholeJPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sizeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pushJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(popJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pushJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(sizeJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(explanationJLabel3)
                            .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(explanationJLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(explanationJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wholeJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                    .addGroup(wholeJPanelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(displayJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(explanationJLabel4)))
                .addContainerGap())
        );
        wholeJPanelLayout.setVerticalGroup(
            wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholeJPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeJButton)
                    .addComponent(explanationJLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pushJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pushJButton)
                    .addComponent(explanationJLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popJButton)
                    .addComponent(explanationJLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(wholeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayJButton)
                    .addComponent(explanationJLabel4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pushJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pushJButtonActionPerformed
    {//GEN-HEADEREND:event_pushJButtonActionPerformed
        try
        {
            stackObject.push(Integer.parseInt(pushJTextField.getText()));
            pushJTextField.setText("");
            displayJButtonActionPerformed(evt);
        }
        catch(Exception e)
        {
            System.err.println( "\n" + e.toString() );
        }
    }//GEN-LAST:event_pushJButtonActionPerformed

    private void sizeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sizeJButtonActionPerformed
    {//GEN-HEADEREND:event_sizeJButtonActionPerformed
        try
        {
            stackObject = new Stack(Integer.parseInt(sizeJTextField.getText()));
            size = Integer.parseInt(sizeJTextField.getText());
            sizeJTextField.setText("");
            displayJButtonActionPerformed(evt);
        }
        catch(Exception e)
        {
            System.err.println( "\n" + e.toString() );
        }
    }//GEN-LAST:event_sizeJButtonActionPerformed

    private void popJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_popJButtonActionPerformed
    {//GEN-HEADEREND:event_popJButtonActionPerformed
       try
       {
           stackObject.pop();
           displayJButtonActionPerformed(evt);
       }
       catch(Exception e)
       {
            System.err.println( "\n" + e.toString() );
       }
    }//GEN-LAST:event_popJButtonActionPerformed

    private void displayJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_displayJButtonActionPerformed
    {//GEN-HEADEREND:event_displayJButtonActionPerformed
       
//      for(int i=size-1; i < 0; i--)
        for(int i=0; i < size; i++)
        {
            display.append(stackObject.contents[i]+ " ");
        }
        stackJTextArea.setText("The elements present in the Stack: \n" + "botton -> peak \n" + display.toString());
        display.delete(0, display.length());
    }//GEN-LAST:event_displayJButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
               StackGUI tennisPlayers = new StackGUI();
               tennisPlayers.setLocationRelativeTo(null);  // locate this program in the center of screen
               tennisPlayers.setVisible(true);
               tennisPlayers.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayJButton;
    private javax.swing.JScrollPane displayJScrollPane;
    private javax.swing.JLabel explanationJLabel1;
    private javax.swing.JLabel explanationJLabel2;
    private javax.swing.JLabel explanationJLabel3;
    private javax.swing.JLabel explanationJLabel4;
    private javax.swing.JButton popJButton;
    private javax.swing.JButton pushJButton;
    private javax.swing.JTextField pushJTextField;
    private javax.swing.JButton sizeJButton;
    private javax.swing.JTextField sizeJTextField;
    private javax.swing.JTextArea stackJTextArea;
    private javax.swing.JPanel wholeJPanel;
    // End of variables declaration//GEN-END:variables

}
